version: 2

models:
  - name: stg_offers
    description: "contains information about the offers"
    tests:
      - dbt_utils.expression_is_true:
          expression: "offervalue >= 0"
    columns:
      - name: offer_id
        description: "An id representing a certain offer"
        tests:
          - not_null

      - name: product_category 
        description: "The product category"

      - name: quantity
        description: "The number of units one must purchase to get the discount"
        tests:
          - assert_column_is_greater_or_equal_to_0
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              row_condition: "offer_id is not null"
              strictly: False
      - name: company_id
        description: "An id of the company that sells the item"

      - name: offervalue
        description: "The dollar value of the offer"
        tests:
          - assert_column_is_greater_or_equal_to_0

      - name: brand_id
        description: "An id of the brand to which the item belongs"

  
  
  - name: stg_transactions
    description: "contains transaction history for all customers"
    columns:
      - name: transaction_id
        description: "A unique id representing a customer"
        tests:
          - not_null
          - unique:
              config:
                severity: warn
                error_if: ">10"
                warn_if: ">5"
                where: "date>'2012-03-01'"

      - name: chain
        description: "An integer representing a store chain"

      - name: dept
        description: " An aggregate grouping of the Category"

      - name: product_category
        description: " The product category"

      - name: company_id
        description: " An id of the company that sells the item"

      - name: brand_id
        description: "An id of the brand to which the item belongs"

      - name: date
        description: "The date of purchase"

      - name: productsize
        description: "The amount of the product purchase"

      - name: productmeasure
        description: "The units of the product purchase"

      - name: purchasequantity
        description: "The number of units purchased"

      - name: purchaseamount
        description: "The dollar amount of the purchase"


  