version: 2

models:
  - name: stg_offers
    description: "contains information about the offers"
    columns:
      - name: offer_id
        description: "An id representing a certain offer"
        tests:
          - not_null

  
  - name: stg_transactions
    description: "contains transaction history for all customers"
    columns:
      - name: transaction_id
        description: "A unique id representing a customer"
        tests:
          - not_null


  