version: 2

models:
  - name: analytics_transactions_yearmonth
    description: "monthly granular results of transactions"
    columns:
      - name: transaction_id
        description: "A unique id representing a customer"
        tests:
          - not_null

  - name: order_by_offervalue
    description: "How much value is each offer"
    columns:
      - name: product_category
        description: "The product category"
        tests:
          - not_null