version: 2

models:
  - name: int_offers
    description:  "The offer table, which contains the consolidated result for offers"
    tests:
    - unique:
        column_name: "concat(product_category, company_id, brand_id)"
    - not_null:
        column_name: "concat(product_category, company_id, brand_id)"

  - name: int_transactions_offers
    description: "an intermediate table which has offered and discounted flags "
    tests:    
      - not_null:
          column_name: "concat(transaction_id, product_category, company_id, brand_id)"
    columns:
      - name: transaction_id
        description: "A unique id representing a customer"
        tests:
          - not_null


  