version: 2

models:
  - name: int_offers
    description:  "The offer table, which contains the consolidated result for offers"
    tests:
    - unique:
        column_name: "concat(product_category, company_id, brand_id)"
    - not_null:
        column_name: "concat(product_category, company_id, brand_id)"

  - name: int_transactions_offers
    description: "an intermediate table which has offered and discounted flags "
    tests:    
      - not_null:
          column_name: "concat(transaction_id, product_category, company_id, brand_id)"
    columns:
      - name: transaction_id
        description: "A unique id representing a customer"
        tests:
          - not_null
      - name: chain
        description: "An integer representing a store chain"

      - name: dept
        description: " An aggregate grouping of the Category"

      - name: product_category
        description: " The product category"

      - name: company_id
        description: " An id of the company that sells the item"

      - name: brand_id
        description: "An id of the brand to which the item belongs"

      - name: date
        description: "The date of purchase"

      - name: productsize
        description: "The amount of the product purchase"

      - name: productmeasure
        description: "The units of the product purchase"

      - name: purchasequantity
        description: "The number of units purchased"

      - name: purchaseamount
        description: "The dollar amount of the purchase"

      - name: offered
        description: "The flag indicates the offer of discount"

      - name: discounted
        description: "The flag indicates the customer had discount"
